### ISSUE TITLE
display type & pinout

### ISSUE THREAD

**Issue by pilnikov** [LilyGO/TTGO-TM-ESP32#1]
Publish please the type (controller) of the display & the schematic diagram (pinout) of its connection to the ESP.  And also the ports to which the buttons are connected.
thanks

**Comment by LilyGO** [comment]
I apologize for my delay. Below I will reply to your question.
The display model is: 2.4" ST7789V LCD
Button keys: pin 37 pin 38 pin39
Of course, the pin map has been placed in readme.md
Again apologize for my negligence. hope this helps.
best wishes

**Comment by bishibashiB** [comment]
I would have values the info here that you will need to pull-down Pin0 for flashing. 
Schematic list '[1]: GPIO0' and could also mention 'Boot'/'Flash'
