### ISSUE TITLE
Possibility to have the schematic

### ISSUE THREAD

**Issue by yeyeto2788** [LilyGO/TTGO-TM-ESP32#5]
Hello guys! 

It would be great to have a full list of the LCD connection since I'm trying MicroPython on the board and I guess have to guess some pin connections.

This is how I initialized the LCD.
`tft.init(tft.ST7735R, speed=10000000, spihost=tft.HSPI, mosi=23, miso=12, clk=18, cs=5, dc=16, rst_pin=17, hastouch=False, bgr=False, width=240, height=320)`

I cannot get touch, also the display show only part of the screen.

Can you guys help me out here?

**Comment by yeyeto2788** [comment]
@LilyGO anyone here?

**Comment by fa1ke5** [comment]
as i know, in this board st7789 display, not of 7735

**Comment by yeyeto2788** [comment]
@fa1ke5 by any chance do you know the pinout/connection of the LCD to the ESP32?

**Comment by fa1ke5** [comment]
on the titul page image pinout is present
you may see p.[4]

**Comment by yeyeto2788** [comment]
@fa1ke5 I've seen the image but it doesn't say the type LCD screen. I'm also looking for the schematic to see the connection of the backlight pin

**Comment by fa1ke5** [comment]
display type is 7789, as i know backlight is not managed and connected to 3.3v onboard.

**Comment by fa1ke5** [comment]
and good news, display have true fast speed controller, nice work on 40mHz and more....but view angle is so bad (china is china.....)
